name: Tests
on: [pull_request]
jobs:
  test:
    name: test py${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
      - run: |
          pip install poetry
          poetry install
      - run: |
          poetry run flake8
      - run: |
          poetry run pytest
